experiment:
  data_config:
    strategy: fixed
    # train_path: ../datasets/training/train_train.tsv
    # validation_path: ../datasets/training/train_val.tsv
    train_path: ../datasets/training/train.tsv
    test_path: ../datasets/training/test.tsv
  dataset: goodbooks-10k-ext
  top_k: 50
  models:
    ProxyRecommender: 
      path: ../datasets/training/predictions.tsv
  evaluation:
    cutoffs: [50, 25, 10]
    simple_metrics: [nDCG, Precision, Recall, MAP, MAR, MRR]
    relevant_threshold: 0.75 # Tener en cuenta aquellos con rating >= 0.75
    print_results_as_triplets: True
  path_output_rec_result: results/rec_res
  path_output_rec_weight: results/rec_wei
  path_output_rec_performance: results/rec_perf
  path_log_folder: results/log
  # config_test: True # No funciona